name:                nrw
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/jgertm/nrw#readme
license:             BSD3
author:              Tim Jäger
maintainer:          jger.tm@gmail.com
copyright:           2018 Tim Jäger
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - brick
  - microlens-platform
  - mono-traversable
  - optparse-applicative
  - regex
  - regex-with-pcre
  - text
  - universum
  - unix
  - vector
  - vty

executables:
  nrw:
    source-dirs:      src
    main:             Main.hs
    ghc-options:
    - -fllvm
    - -threaded
    - -W
